In [1]:
import numpy as np

In [2]:
id_ary=np.array([1,2,3,4])

In [3]:
print(id_ary)

[1 2 3 4]


In [4]:
type(id_ary)

numpy.ndarray

In [5]:
id_ary.ndim

1

In [6]:
arr=np.array([[1,2,4],[2,4,5]])

In [7]:
print(arr)

[[1 2 4]
 [2 4 5]]


In [8]:
arr.ndim # dimesnsion

2

In [10]:
arr.size # size is for number of the elements

6

In [12]:
arr.shape # number of row and columns

(2, 3)

In [14]:
arr.dtype  # check data type of array

dtype('int32')

In [17]:
z=np.zeros((3,3))     #  bt default float data type

In [18]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
z=np.ones((3,3))

In [20]:
z

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
z=np.full((3,3),10)

In [23]:
z

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [27]:
z=np.empty((3,3))
print(z)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [30]:
# arange
np.arange(1,40)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39])

In [31]:
np.arange(1,40,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [32]:
#linspace

np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [39]:
#reshape
a=np.arange(0,12)
print(a)
a.reshape(2,6)    # check number of elements of reshape array

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [41]:
#convert to 2d

a.reshape((2,3,2))


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [43]:
z=np.arange(0,10).reshape(2,5)

In [44]:
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [45]:
# ravel- convert multidimensional array into 1d
z.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
# flatten-convert multidimensional array into 1d
z.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
# transpose
a=z.transpose()
pe
print(a.shape)

(5, 2)


# mathematic operation using NumPy

In [1]:
import numpy as np


In [2]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(1,10).reshape(3,3)

In [4]:
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
arr1+arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [6]:
np.add(arr1,arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [9]:
np.subtract(arr1,arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [10]:
np.divide(arr1,arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
arr1*arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [12]:
np.multiply(arr1,arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [14]:
arr1 @ arr2 # matrix product

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [15]:
arr1.dot(arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [16]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr1.max()  # maximum element

9

In [22]:
arr1.argmax()  # find index of the maximum value

8

In [23]:
arr1.max(axis=0)  # column wise maximum value

array([7, 8, 9])

In [24]:
arr1.max(axis=1)  # row wise maximum value

array([3, 6, 9])

In [26]:
arr1.min()

1

In [27]:
arr1.argmin()

0

In [28]:
arr1.min(axis=0)

array([1, 2, 3])

In [29]:
arr1.min(axis=1)

array([1, 4, 7])

In [30]:
np.sum(arr1)

45

In [31]:
np.sum(arr1,axis=0)  # sum column wise

array([12, 15, 18])

In [32]:
np.sum(arr1,axis=1)

array([ 6, 15, 24])

In [33]:
np.mean(arr1)

5.0

In [34]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [35]:
np.std(arr1)

2.581988897471611

In [36]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [37]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [38]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])