In [1]:
import numpy as np

In [2]:
import random

In [3]:
np.random.random(1)   # values only between 0 and 1

array([0.13631881])

In [4]:
np.random.random(5)

array([0.2834452 , 0.10635385, 0.16409348, 0.76787266, 0.19694552])

In [5]:
np.random.random((3,3))

array([[0.4645761 , 0.88168533, 0.22806202],
       [0.56070438, 0.36097725, 0.46258083],
       [0.30528052, 0.61311014, 0.8907514 ]])

In [6]:
np.random.randint(1,5)  # range mai se koi value dega

3

In [9]:
np.random.randint(1,100,(4,4))

array([[66, 54, 20, 24],
       [15, 44,  3,  2],
       [30, 25, 70,  1],
       [49, 58, 29, 79]])

In [10]:
np.random.randint(1,100,(2,4,4))

array([[[47, 69, 44, 16],
        [64, 34, 16, 67],
        [27,  1, 81, 83],
        [25, 18,  6, 30]],

       [[69, 64, 48, 30],
        [64, 99, 43, 70],
        [87, 14, 85, 35],
        [72, 70, 89, 23]]])

In [11]:
np.random.seed(10)
np.random.randint(1,100,(2,4,4))

array([[[10, 16, 65, 29],
        [90, 94, 30,  9],
        [74,  1, 41, 37],
        [17, 12, 55, 89]],

       [[63, 34, 73, 79],
        [50, 52, 55, 78],
        [70, 14, 26, 14],
        [93, 87, 31, 31]]])

In [12]:
np.random.seed(10)
np.random.randint(1,100,(2,4,4))

array([[[10, 16, 65, 29],
        [90, 94, 30,  9],
        [74,  1, 41, 37],
        [17, 12, 55, 89]],

       [[63, 34, 73, 79],
        [50, 52, 55, 78],
        [70, 14, 26, 14],
        [93, 87, 31, 31]]])

In [13]:
np.random.rand(3)    # create nd array with values 0 se 1 

array([0.82608225, 0.10540183, 0.28357668])

In [14]:
np.random.rand(3,3) 

array([[0.06556327, 0.05644419, 0.76545582],
       [0.01178803, 0.61194334, 0.33188226],
       [0.55964837, 0.33549965, 0.41118255]])

In [15]:
np.random.randn(3,3) 

array([[-1.02094527, -0.16206903, -0.6579709 ],
       [ 0.42211306,  0.62402334,  0.5016401 ],
       [ 0.84143473, -1.64024998,  1.05800516]])

In [16]:
x=[1,2,34,5]
np.random.choice(x)

34

In [17]:
np.random.permutation(x)

array([ 5,  1,  2, 34])

In [18]:
np.random.permutation(x)

array([ 2,  5,  1, 34])